FROM nocalhost-docker.pkg.coding.net/nocalhost/dev-images/java:11

ARG java_agent_version=v1.23.0

ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/${java_agent_version}/opentelemetry-javaagent.jar /
